### ISSUE TITLE
net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by fridzema** [crabbly/Print.js#101]
Hello,

I am serving a pdf response on a certain page. When i call this page with type pdf i get the following error in the console: 
`net::ERR_NAME_NOT_RESOLVED`

The get request failed, and a warning is displayed: 
`Resource interpreted as Document but transferred with MIME type application/pdf`

But when i print from the dialog everything is fine!
Maybe its an idea not to check explicit on .pdf extension?

**Comment by crabbly** [comment]
@fridzema Hey Robert, yea I have been ignoring the `Resource interpreted as Document but transferred with MIME type application/pdf` warning because it doesn't affect the job. 

However, I never got a `net::ERR_NAME_NOT_RESOLVED` error, it must be something else. 
Could you please give me more info, I would love to find out what's happening and hopefully fix this:
Are you passing the correct pdf url to the `printJS` function? 
Also, do you see the the code line where this error is coming from? 
Are you using the loading message (`showModal` set to `true`)?

Thx.

**Comment by fridzema** [comment]
@crabbly Thank for your fast reply!
I am very sorry, the problem was that i used an absolute UR for the pdf.
Everything working fine now :)

**Comment by crabbly** [comment]
Glad to hear :)
