### ISSUE TITLE
Print html content with images

### ISSUE THREAD

**Issue by kingringc** [crabbly/Print.js#109]
Images in the html is not printing right now, do we need to add a delay to render that ? please help me.

**Comment by kingringc** [comment]
ok, adding a delay seems to be working.

**Comment by crabbly** [comment]
@kingringc Hey Chandrasekar, it may be because the images were not yet loaded. However, when printing HTML, the images should already be cached by the browser, which would prevent the need of any delay. 
Unless the images have headers set to prevent cache. 
Is this the case with the images in your html? 

I'll run some tests to confirm this.

**Comment by crabbly** [comment]
@kingringc Hey Chandrasekar, I finally got to this, and after running some tests, I found no issues with printing html with images. 

I created a fiddle as an example:
https://jsfiddle.net/crabbly/9dwpd4g1/

I tested in Chrome, Safari, Firefox and Opera.
