### ISSUE TITLE
isFirefox used as variable in condition

### ISSUE THREAD

**Issue by jmas** [crabbly/Print.js#11]
I guess there should be a `isFirefox` call, not just a check for function exists.
https://github.com/crabbly/Print.js/blob/master/src/print.js#L223

**Comment by crabbly** [comment]
@jmas Hey Alexander, this isn't a "function exists", it instead, uses the returned value from the function for the conditional. When the browser is Firefox, the function will return `true`. And of course, it will return `false` for any other browser. The values `true` or `false` will be used by the `if` statement.
I don't see a problem using functions with if statements, however, I'm wondering why you would think otherwise. Am I missing anything here?
I'll wait for you input before I close this issue.
Thank you.

**Comment by crabbly** [comment]
@jmas I'll close this since it doesn't look like an issue with the library. Thank you.
