### ISSUE TITLE
"main" entry in package.json should not be minified

### ISSUE THREAD

**Issue by sloria** [crabbly/Print.js#123]
The "main" entry is currently pointing to a minified build.

Better practice is for "main" to be the unminified UMD build and leave it up to developers to minify it within their build process. This allows for easier debugging during development.

If you want, you can still publish a minified version in dist/ , but it shouldn't be the "main" entry in package.json.

**Comment by crabbly** [comment]
@sloria , Hey Steven, I agree. 
However, some people were having issues because their compilers wouldn't properly process ES6. After we added the minified version to the "main" entry, I haven't received any reports about it.

I know this issue isn't the library responsibility, but it seems to have helped people that don't yet work with ES6. For such a small library, I thought it would be ok.

**Comment by sloria** [comment]
Oh, I didn't mean that you need to distribute the uncompiled ES6 module. I meant that you should distribute the *unminified* UMD build as the "main" entry.

**Comment by crabbly** [comment]
Ohhh, got it. Thx. 
We would need to add a second compiled file then. The _unminified_ version to be used in "main". I guess it could be placed in the `dist` folder.

**Comment by crabbly** [comment]
Hey Steve, I added the non-minified file and used it in the package.json "main" field.
Please let me know if you find any issues with it.
I'll publish a new release soon.
Thanks again for your help.

**Comment by sloria** [comment]
Great!

As a follow-up: it'd be better to not add `dist/` to version control; it only adds noise in the git history. I'll open another issue.
