### ISSUE TITLE
Firefox only print one page - JSON

### ISSUE THREAD

**Issue by lfmontalvan** [crabbly/Print.js#128]
I'm trying to print in mozilla firefox, everything works fine ... I correctly load the json, I send it to print, I select the correct printer but when printing only the first page is printed, in chrome I try the same and it is visualized that it is 4 pages. .. please ... how can I make firefox print the necessary pages?

**Comment by lfmontalvan** [comment]
my regards genius crabbly...!!!

**Comment by crabbly** [comment]
@lfmontalvan I just tested a multi-page JSON print and confirmed the bug with Firefox. However, this bug seems to be with Firefox, when printing iframe data longer than one page size. There are a couple of bugs opened with Mozilla. Here is one that has been opened for years: https://bugzilla.mozilla.org/show_bug.cgi?id=113217

I'll try to find a work around for this issue in Firefox. 
Hopefully, there is a way to make it work. 

I also tested this in Chrome, Opera and Safari with Mac OS, and they worked fine.

**Comment by gharibi** [comment]
@crabbly I have opened a pull request with some enhancement to the json printable type. In this version, I have resolved this issue.

**Comment by crabbly** [comment]
@lfmontalvan I just published v1.0.38 to npm with the changes made by @gharibi . He fixed the issue with printing multiple pages with JSON data. Please run `npm update print-js` and give it a try. Reopen this if you are still having issues after trying the new release.

Thank you for the fix, Arash. 💯 @gharibi
