### ISSUE TITLE
Problem printing with Google Chrome Version 65.0.3325.146

### ISSUE THREAD

**Issue by luispire** [crabbly/Print.js#133]
Today, I have a problem printing with Google Chrome versión 65.0.3325.146. The page shows white and no charge info. 

Thanks.

**Comment by crabbly** [comment]
Which OS and version?

**Comment by luispire** [comment]
MacOS 10.13.3, Windows 7,  Windows 8 and Windows 10

**Comment by gdazaf** [comment]
I'm having the same problem with the new Google Chrome v. 65.0.3325.146. Send to print and shows empty preview. OS: MacOS 10.13.3, Win7 to 10.

**Comment by crabbly** [comment]
I just confirmed. Looks like the latest version of Chrome, v65, is not printing any iframe data, therefore a blank page. Not sure what to do about this yet.

**Comment by igormages** [comment]
Someone found something ?

**Comment by igormages** [comment]
I found a solution ! I'll put the result here tonight :)

**Comment by igormages** [comment]
It's even simpler than I was thinking. At the moment printJS load a invisible iframe, and focus on int and print the frame right ? I just used a visibility: hidden instead a display: none, and that works again. Can you try that ?

**Comment by luispire** [comment]
It's great, It worked for me correctly. Thank you very much.

**Comment by crabbly** [comment]
@igormages Thank you Igor, this did the trick. I had to add `height:0` and `width:0` to prevent changes in the page layout, since using `visibility:hidden` doesn't completely remove the iframe from the page. Event with these settings, the iframe may still move the current page up a little. I will try to add a hook method to remove the iframe once the print job is complete.
I already pushed the change to npm. Thanks again.

**Comment by kyriacos** [comment]
@crabbly I know this PR is closed but just wanted to add another suggestion. Adding `position:absolute` takes care of the slight height increase. Doesn't seem to move the page up at all. Still needs`height:0;width:0;`. 

And when removing the iframe in IE it also avoids the slight page jump which happens when the user is scrolled all the way to the bottom of the page.

Thanks for the fix! :)

**Comment by crabbly** [comment]
@kyriacos Nice! 
I'll test it out and implement in the next release.
Thank you, Kyriacos.
