### ISSUE TITLE
Modal Decoding HTML

### ISSUE THREAD

**Issue by msopko81** [crabbly/Print.js#14]
It would be nice to allow for the modalMessage to be HTML code. This way loading gifs can be used or, in my case, font awesome. I tried to set modalMessage to '<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>', but this is printed out instead of the image.

**Comment by crabbly** [comment]
I like it. Will implement this in the future. Thank you.

**Comment by crabbly** [comment]
@msopko81 , we added hooks to before and after the loading of PDF files. This should allow you to initiate your own HTML modal, and then close it once the PDF is loaded. Instead of using the `showModal` parameter, you can instead use `onLoadingStart` to open your modal, then `onLoadingEnd` to close your modal.

Both `onLoadingStart` and `onLoadingEnd` should be functions that will control the showing and hiding of your HTML modal.

http://printjs.crabbly.com/#configuration
