### ISSUE TITLE
Scroll Bar appears after calling print function

### ISSUE THREAD

**Issue by CollinKendor** [crabbly/Print.js#148]
Hi,

I noticed there the scrollbar for the body (i.e. body tag) will appear after the print dialog appears and it won't go away until I refresh my page. I was printing some data in json. I am unable to determine the cause of this strange behavior. Perhaps you will be able to help.

**Comment by crabbly** [comment]
Hey @CollinKendor , this is probably happening because we no longer use `display: none;` to hide the iframe. Since we changed it to fix other issues when printing HTML, I don't want to change it back. I think we may be able to just delete that iframe after we print. The challenge is to find out when the the job is finished, to prevent deleting the iframe before everything has been processed. I'll take a look into this.

**Comment by CollinKendor** [comment]
Hi crabbly,

Thanks for the reply. I discovered the iframe when I console.log my div tag and am currently working on a workaround. 

At least now I have something to tell my customer. I am a very fussy customer at hand. Thank You once again.

**Comment by crabbly** [comment]
Cool. I'll let you know once I push a new solution. In the meantime, you could use v1.0.31, which is a couple of versions earlier, before we made that change. That version still hides the iframe with `display: none;`, which shouldn't break the page layout after printing.

**Comment by CollinKendor** [comment]
Thanks for the recommendation. found something that might help you.

https://www.w3schools.com/jsref/event_onafterprint.asp

**Comment by crabbly** [comment]
Thank you. I have played with this before, it was very reliable, unfortunately. Also, it is not supported by Safari and Opera.

**Comment by crabbly** [comment]
Hey @CollinKendor , the latest version should have fixed this issue. Please run `npm update print-js` to get it. If you are still having issues with it, please reopen this issue. Thank you.
