### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by younas-bangash** [crabbly/Print.js#15]
Error in below line

import * as browser from './browser'

**Comment by crabbly** [comment]
@younas-bangash  I'm not getting any errors with this. Could you please post the error message here? Thank you.

**Comment by Neobugu** [comment]
print.js:11 Uncaught SyntaxError: Unexpected token import

import { print } from './js/print'

window.printJS = print

**Comment by crabbly** [comment]
Hey @Neobugu and @younas-bangash , this error is because the library is using ES6 modules. You may want to start using it.
http://exploringjs.com/es6/ch_modules.html

In the mean time, I changed the library to use `require` instead. This will probably fix the issue for your current environment. Please try the latest release.
https://github.com/crabbly/Print.js/releases/latest

Eventually, I'll probably change it to use `import` again.

**Comment by crabbly** [comment]
@Neobugu @younas-bangash If you like the library, please star the project. Thank you.
