### ISSUE TITLE
print type html height is different print preview hieght

### ISSUE THREAD

**Issue by WwJoyous** [crabbly/Print.js#199]
thanks author.
 i want to add watermark  the html. i used css 'position:absolute'. the html normal ,but print preview height 
not full coverage. Last few pages no watermark.
[you can look my code](https://github.com/WwJoyous/print-demo):https://github.com/WwJoyous/print-demo

**Comment by crabbly** [comment]
Hi @WwJoyous , 
I'm confused. Do you have two issues? 
One with the html height and another with trying to add watermark? 

I quickly looked at your code but can't see where the problem is there. Unfortunately I don't have time to go over your watermark logic.

If you replicate the issue in a fiddle, or add screen shots of your print results here, I maybe able to help you more.
