### ISSUE TITLE
Custom property name on table header

### ISSUE THREAD

**Issue by vitorhorta** [crabbly/Print.js#207]
Is it possible to customize the column names in the table header?
For example I'm printing using nested objects and instead of printing "Company.Name" it would be nice to print only "Company".

This would also be useful when printing in another language.

**Comment by crabbly** [comment]
Hi Vitor,
This isn't available yet. However, we have already merged a PR implementing this feature. The only reason it isn't available on npm yet, is because this PR breaks the API. Which would be a problem for people that are currently using the library to print JSON data. I'm adapting it to be backwards compatible, and will release it soon. 

I'll post an update here once this is available. 
PR: https://github.com/crabbly/Print.js/pull/180

**Comment by crabbly** [comment]
Hi Vitor, I just published version 1.0.48 with the update. The lib now supports properties as objects for customization. I'll update the documentation soon, but in the meantime, here is a fiddle showing how to customize the property labels.

https://jsfiddle.net/crabbly/bLq52fyu/

Let me know if any issues.

**Comment by crabbly** [comment]
Thanks to @gharibi for helping with this feature.
