### ISSUE TITLE
Can't print images when the type is "html"

### ISSUE THREAD

**Issue by CharlesYwj** [crabbly/Print.js#213]
When I used **PrintJS** to print DOM elements,I find that it can't print images them in DOM element.I check the source code,for the reason, it may be the images is not in loaded status while function `Print.send` is running .

My page:
![image](https://user-images.githubusercontent.com/13976900/44447637-5f6b5e80-a61b-11e8-9300-3ae50fd86a5c.png)

Print preview Page:
![image](https://user-images.githubusercontent.com/13976900/44447657-6e521100-a61b-11e8-9a70-72a6025f622f.png)

**Comment by crabbly** [comment]
Hi @CharlesYwj ,

The library won't preload the images when printing html because they are already loaded in the browser. When printing the html with images, the library should just receive the images from the browser cache.

Here is a fiddle showing the lib printing html with images:
https://jsfiddle.net/crabbly/uck6ur3z/

Please make sure your image isn't set as the element background. If that's the case, it may not be printed because the browser default settings won't include background colors and images.
