### ISSUE TITLE
Can't print the image from api

### ISSUE THREAD

**Issue by WilliamTsee** [crabbly/Print.js#220]
![image](https://user-images.githubusercontent.com/42863273/44904299-7871bf00-ad41-11e8-98d6-ed7077b1c54f.png)
![image](https://user-images.githubusercontent.com/42863273/44904337-963f2400-ad41-11e8-86b4-fc34507b0d6e.png)
I used Print.js to print a form .The static image can be print，but the image from api can't.

**Comment by crabbly** [comment]
Hi @WilliamTsee , it doesn't matter how the image was loaded into the browser. The library will print it the same.

Here is an example showing the lib printing html with two images. One of them is returned from an API endpoint:
https://jsfiddle.net/crabbly/mLyqnLr1/

However, if images are not cached, this could be a problem. This is because the library will create a copy of the html into an iframe, and then print that iframe. If the image is not cached, the print job could fire before the image is loaded inside the iframe.

**Comment by WilliamTsee** [comment]
Thanks，maybe i know the problem. The image from local area network test environment can't work.but it from external network environment can.

**Comment by crabbly** [comment]
The issue is probably related to the API response headers.
