### ISSUE TITLE
Images are not printed when loaded from a static folder

### ISSUE THREAD

**Issue by ketimaBU** [crabbly/Print.js#236]
When the type of printed page  is *html*, the images in it are not printed if they are loaded from a static folder
```
    <div id="tickets">
            <h2>A test print</h2>
            <img class="ticketLogo2" src="url to a png " alt="ticketLogo2">
            <img class="ticketLogo1" src="/static/images/ticket.png" alt="ticketLogo1">
    </div>
```
 I am using this JS code:
```
        printJS({ printable: 'tickets',
            type: 'html',
            css: '/static/css/styles_tickets.css'});
```
The first Image is shown in the printing page while the second doesn't appear.

**Comment by crabbly** [comment]
Hey @ketimaBU , the images should work the same way, however, when using a relative path, it must be full path on the domain.

For example, if the current page is in `/my-section/my-page.html`, and the images are in `/my-section/images`, the path passed in must be `my-section/images` and not `images`. 

Take a look at the documentation page how it uses the path in the images example:
http://printjs.crabbly.com/#image

The image path is http://printjs.crabbly.com/images/print-01-highres.jpg

But we just passed the `images/print-01-highres.jpg` path to `printJS`:

`printJS('images/print-01-highres.jpg', 'image')`

This is using what you are calling a 'static folder'. Just adapt your path and you should be good.
Let me know how it goes.

ps.: I would recommend omitting the domain and using a relative path when the images are under the same domain. This is because if the business domain changes, you don't need to change your code.

**Comment by crabbly** [comment]
Hey, @ketimaBU , I'm closing this as I believe it is not an issue related directly to the library. Feel free to open it again if necessary. Thx.
