### ISSUE TITLE
JSON document title not printed IE11

### ISSUE THREAD

**Issue by yurien1986** [crabbly/Print.js#270]
When using the JSON printing feature on IE11, I get the classic IE pop-up displayed for printing, after I print,  the title I provided in the documentTitle field is not being printed.

As we don't have the print preview feature on IE, you should print a document to reproduce it.

Thanks for providing this amazing library.

**Comment by crabbly** [comment]
Hey @yurien1986, thank you for reporting this issue. 
I'll test it as soon as I can. Hopefully, we can do something about it and update the lib.

**Comment by vschimpf** [comment]
Same for me, any news?

**Comment by crabbly** [comment]
It seems like IE won't respect this request. It prints the JSON data, but the `documentTitle` feature will not work with IE. I'm not sure what else we can do to make this feature work on IE. For now, I would just say that the `documentTitle` feature is not available for IE, unfortunately. 

The browser compatibility table is focused on the features alone, therefore we can't add this information there.
https://printjs.crabbly.com/#browsers
Maybe we could update the params descriptions with an option to specify browser issues related to each specific option. 
Closing this issue for now since i'm not able to dedicate time to add this support. A PR for a possible fix or the documentation update would be welcomed. Thank you.
