### ISSUE TITLE
Issues using external stylesheet

### ISSUE THREAD

**Issue by conangithub** [crabbly/Print.js#285]
I use print.js to print my html page. But why the text color can't be printed? The rest css style is no problem.

My CSS
```
#tax td{
      color: #518cb8 !important;
}
```

My print.js
```
$(function(){
            printJS({
                printable: 'print-area',
                type: 'html',
                css: ['https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
                      'https://fonts.googleapis.com/css?family=Open+Sans:400,700'
                ],
                targetStyles: ['*']
            });
        });
```

My html
```
<table>
    <tfoot>
         <tr id="tax">
                <td colspan="4">Tax Base</td>
                <td class="text-right">5000</td>
         </tr>
     </tfoot>
</table>

```

**Comment by crabbly** [comment]
Hi @conangithub, 

Try passing all your css through the `css` property, and disable the library style processing.

Ex.: 

```js
printJS({
    printable: 'print-area',
    type: 'html',
    css: [
    	'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
      	'https://fonts.googleapis.com/css?family=Open+Sans:400,700'
      	'/css/my-website-stylesheet.css'
    ],
    scanStyles: false
})
```

This will also be faster since it prevents the client / library from running some javascript code to retrieve all the applied style on your html.

**Comment by conangithub** [comment]
But when I use `scanStyles: false`, some of my css doesn't work. Like my font that I use
`'https://fonts.googleapis.com/css?family=Open+Sans:400,700'`.

**Comment by crabbly** [comment]
Are you passing an array with the `css` property, where one of the array items is `https://fonts.googleapis.com/css?family=Open+Sans:400,700`?

**Comment by conangithub** [comment]
As the code shown previously :
```
printJS({
    printable: 'print-area',
    type: 'html',
    css: [
    	'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
      	'https://fonts.googleapis.com/css?family=Open+Sans:400,700'
      	'/css/my-website-stylesheet.css'
    ],
    scanStyles: false
})
```
I put `https://fonts.googleapis.com/css?family=Open+Sans:400,700` in `css` array. When I use `scanStyles: false`, my font style not working. Any idea to help me?

**Comment by crabbly** [comment]
I created a codesandbox for this:
https://codesandbox.io/s/8k57kx0n52

Looks like the issue is that the print job is firing before the font is available / loaded inside the iframe. 
It will fail on the first print job, but if you try to print again, it works on the second print job.

Since the font was already loaded when displaying the page (at least on this sandbox example), I'm wondering why it didn't just retrieve it from cache for the first print job. Ideas?

**Comment by conangithub** [comment]
So, that's mean I need to put the PrintJS function not in the html loading event but after the html loaded successfully, right?

I also click the print button. At the first print, the 'google-font' class also didn't show and at next print it showed. Don't have idea about this.

**Comment by crabbly** [comment]
It doesn't matter where you put the `printJS` function. The issue is related to the external stylesheet not being loaded / available when the print event is fired.

**Comment by conangithub** [comment]
So, will it be fixed?

**Comment by crabbly** [comment]
Hopefully. Feel free to submit a PR :)

**Comment by conangithub** [comment]
I currently busy. Hopefully others can contribute to this issue.

**Comment by crabbly** [comment]
Proposed solution for this on dev:
https://github.com/crabbly/Print.js/commit/0df06c5720334750e35b2087deb382975259bee0
It needs to be tested.

**Comment by crabbly** [comment]
Preloading google font style sheets in JavaScript won't work aways, since the style sheet itself may then retrieve the font from an external url.

For example, the style sheet that you are using, `https://fonts.googleapis.com/css?family=Open+Sans:400,700` may have to retrieve this guy `https://fonts.gstatic.com/s/opensans/v16/mem8YaGs126MiZpBA-UFWJ0bf8pkAp6a.woff2`, and preloading the style sheet itself won't preload the font, therefore, not fixing the missing font issue.

**Comment by asinger777** [comment]
I just want to add to this issue -- all of my styles coming from a few different stylesheets are working fine, except for one google font (in one class). I'm only using targetStyles: ['*'] -- not css: []. I tried passing stylesheets in the css array, but that didn't work for me, for some reason.

**Comment by crabbly** [comment]
Hey @asinger777, 

Google fonts require an external font within the external stylesheet. The library won't be able to preload them, as explained in my previous comment.

I'm not sure how we can fix this issue. This commit has a solution to preload stylesheets, but adding this to the library wouldn't fix the external stylesheet font dependency: https://github.com/crabbly/Print.js/commit/0df06c5720334750e35b2087deb382975259bee0

**Comment by melancholyfleur** [comment]
Hi @crabbly,
I am interested in testing out your commit here, because my issue is with fonts that are internal to the app, so I think this fix would work. However, when I pull in the commit directly into my Rails project via `yarn add git@github.com:crabbly/Print.js.git#0df06c5720334750e35b2087deb382975259bee0` the asset pipeline doesn't work as expected because the files aren't in a `dist` folder. 

Specifically, it breaks on this line `//= require print-js/dist/print.js` in `app/assets/javascripts/application.js` with this error: `ActionView::Template::Error (couldn't find file 'print-js/dist/print.js' with type 'application/javascript'`
When I try to point it to the right file `print-js/src/js/print.js`, it fails in the browser with this error: `Uncaught SyntaxError: Cannot use import statement outside a module`

Do you know of a way to pull in the commit and still have it work in a Rails project? Any guidance here would be greatly appreciated.

Thanks!

**Comment by melancholyfleur** [comment]
Update: I was able to just make the changes directly to the file in my local repo to see if they work. The change does seem to help load the fonts internal to the application inside the iframe. Would you be able to either put together a PR with that commit or review one if I put it together, @crabbly?

**Comment by conangithub** [comment]
I close this issue. I am sorry. I already used other library.
