### ISSUE TITLE
Properties to set imageHeader and imageHeaderStyle

### ISSUE THREAD

**Issue by JandersonConstantino** [crabbly/Print.js#289]
Hi,
I would like to propose the create two new properties: 
- imageHeader: A image to set in the header, a logo for example.
- imageHeaderStyle: to set CSS of the image in plain text (as are in other properties).

If add the imageHeader property, the result are:

```javascript
/// Image url
const imageHeader = 'https://via.placeholder.com/350x65'

// Print from JSON
handlePrintJSON = () => {
    const arr = [
      { name: 'Janderson Constantino', email: 'jandersonconstantino@gmail.com' },
      { name: 'Lorem Ipsum', email: 'lorem.ipsum@gmail.com' },
    ]

    printJS({
      printable: arr,
      imageHeader,
      properties: [
        { field: 'name', displayName: 'Name', },
        { field: 'email', displayName: 'E-mail', },
      ],
      type: 'json'
    })
  }
```

![image](https://user-images.githubusercontent.com/15123834/55003155-9ab97b80-4fb6-11e9-9f80-01e6158303ce.png)

**Comment by JandersonConstantino** [comment]
- [x] Open issue
- [x] Open Pull Request
- [ ] Merged Pull Request
- [ ] Update Documentation

**Comment by crabbly** [comment]
@JandersonConstantino 
Hi Janderson, 
First, thank you for helping with the library! 💯 

I like the idea of adding the option of passing an image to be be posted on top of the JSON table. I think we can improve your idea and improve the current `header` property to accept raw HTML instead of text only. We could do a quick check on the header content to confirm if its just text or raw html. If it's just text, we handle it just like we currently do, by adding a header tag to it. If its html, we just use it as it was passed in. This would prevent the extra properties and keeping the library api as small as possible.

When it comes to the second proposed property, `imageHeaderStyle`, we should just use the `style` and `css` instead. I'm actually deprecating all the properties related to style. The last one will be the `headerStyle` property. Using the `style` and `css` properties give us a lot more freedom to style the print job.

What are you thoughts on this?

**Comment by JandersonConstantino** [comment]
@crabbly I consider the best way, I will go make these changes and send a new PR.

**Comment by crabbly** [comment]
Awesome! :)
Thank you, Janderson.
