### ISSUE TITLE
Images not printed in landscape / able to change orientation

### ISSUE THREAD

**Issue by bogal** [crabbly/Print.js#308]
I am using this plugin to try and print dispatch labels.
Each label is behind a secure gateway, so the uri for each image is something like mydomin/view-image/34 which outputs a PNG image (as opposed to a "hard-coded" image uri like mydomin/images/34.png).

When i send this uri to printJS i find that it will only print the image in portrait orientation, and in doing so reduces the size of it to about 25%.

When i specifically define landscape via css, the label is printed blank.

My code:
```
printJS({
    printable: imageSrc,
    type: 'image',
    style: '@page { size: auto landscape; }'
});
```

I should also add that even the fiddle provided in [#258 ](https://github.com/crabbly/Print.js/issues/258) is printed in portrait and not landscape. 
Printer is a ZDesigner GK420d, from Win 10.

**Comment by bogal** [comment]
Just to add that even i rotate the image via css, it is still printing out around 25% of it's actual size:

```
printJS({
    	printable: imgSrc,
    	type: 'image',
    	style: "@page { size: auto landscape; }",
	imageStyle: "width: 100%;  transform: rotate(90deg)"
});
```

**Comment by crabbly** [comment]
Hey @boga,

Thank you for all the info.
I checked the example you have mentioned, and it prints landscape for me. As expected.
https://jsfiddle.net/crabbly/Lvktrb5n/

The library doesn't do anything special when it comes to page orientation. It just passes the input `css` or `style` to the print job. As long the style / css passed is respected by the browser, it should perform as expected.

About the image reduction, it maybe because of the default `maxWidth` set to `800px`. 
This is going to be removed form the library. There will be not printing defaults. We can alway pass a print style sheet if necessary.

That said, try this:

```
printJS({
    printable: imageSrc,
    type: 'image',
    style: '@page { size: auto landscape; }',
    maxWidth: 1000
})
```

That would expand 25% the max width. Play with it though.  Hope this helps.

**Comment by crabbly** [comment]
Closing this as I believe the issue can be solved by passing the print width to the lib. Feel free to reopen if necessary.

As a note, we will be removing the default `maxWidth` value from the library. Documentation will be updated once this change is done.
