### ISSUE TITLE
PDF printing in Chrome does not work if "Download PDF" is selected in preferences

### ISSUE THREAD

**Issue by mehl** [crabbly/Print.js#316]
Steps to reproduce:

1. Open chrome://settings/content/pdfDocuments
2. Choose "Download PDF" instead of direct embedding 
3. Open https://printjs.crabbly.com/#pdf
4. Try to print a PDF from there, it does not work, but gives a "cross origin" error in the console.

![Bildschirmfoto von 2019-05-13 14-52-18](https://user-images.githubusercontent.com/2109958/57626552-644fb400-7596-11e9-9d6f-6f4c52b9d69e.png)

Tested with current Chromium and Chrome versions.

**Comment by crabbly** [comment]
Hey @mehl, the library fetches the PDF document to be able to use it / fire the print job.
If the browser is forcing the download, this will block us from printing the PDF. In fact, even if we try to open the PDF in a new tab, for the user to manually print the file, this won't work as well, since the browser will force the download.

That said, if this option is set, there is no way for us to print the PDF from the browser.

**Comment by crabbly** [comment]
What version of the library are you using?

**Comment by mehl** [comment]
We updated now to the most current version of the library. IMHO there should be at least some hint to the user that printing does not work because of this. It took us quite some time to figure this out.

We now force our users to change this browser option...

**Comment by crabbly** [comment]
@mehl I agree. That would be awesome. I would love to implement this into the library.

In the meantime, you know you could handle this in your side correct?
Check for this setting, and then fire the print job or inform the user.

Feel free to post any implementation / suggestions here.
A PR would be welcome! :)

**Comment by worthy7** [comment]
@crabbly How can we check that setting?

**Comment by crabbly** [comment]
Closing this issue this this is related to a user browser setting and cannot be controlled by the library.
