### ISSUE TITLE
If the address of the image does not exist, it will not evoke the print window.

### ISSUE THREAD

**Issue by wuanyang** [crabbly/Print.js#336]
this type = "html"
```
<div>
    <img src="" alt="">
</div>
```

**Comment by crabbly** [comment]
Hey @wuanyang, 

Thank you for reporting this.
The job fails because the library was waiting for the image to be loaded. 
I added a check to make sure the image src is valid before trying to load the image. If the src is invalid, the lib will skip that one image and proceed with the print job.
https://github.com/crabbly/Print.js/commit/c16e2385f65322b3e81c8e2b0bb9ce292d41b7a4

This will be available with the next release. Thx again.

**Comment by wuanyang** [comment]
This problem is solved, can you release a new version? My project needs to solve this problem。
