### ISSUE TITLE
Some styles do not take effect

### ISSUE THREAD

**Issue by a15218378694** [crabbly/Print.js#350]
example: flex layout, line-height, last font is in newline(different layout has different view)
![printBefore](https://user-images.githubusercontent.com/29919045/60075741-938e3f00-9758-11e9-82c7-03405fd94199.jpg)
![printePage](https://user-images.githubusercontent.com/29919045/60075743-9426d580-9758-11e9-906e-dff66b80b93c.jpg)
![hasProblem](https://user-images.githubusercontent.com/29919045/60077207-0b119d80-975c-11e9-89d6-fd0c811af5c8.jpg)
![noProblem](https://user-images.githubusercontent.com/29919045/60077208-0b119d80-975c-11e9-9732-0f832c724f8d.jpg)
![noProblemView](https://user-images.githubusercontent.com/29919045/60077273-309ea700-975c-11e9-9782-febc173b05c3.jpg)

**Comment by ryanlin1986** [comment]
Vote up for this as well, style referenced from external url losts

**Comment by sneha-nerekar** [comment]
Even inline styles are not reflecting while rendering

**Comment by crabbly** [comment]
@sneha-nerekar Inline style is working. You can try the examples available in index.html under test/manual.

Also, here is a sandbox printing a styled html using both the `css` and `style` properties:
https://codesandbox.io/s/printjs-styled-html-l0yk8

Here is a fiddle as well:
https://jsfiddle.net/crabbly/gqjqh1gn/27/

@a15218378694 The sandbox linked above shows an example printing styles html using flexbox. The implementation should process any style, there isn't any limitation since it just pass it to the iframe so the browser can print as normal.

@ryanlin1986 External urls shouldn't be an issue if it's passed directly. The lib will try to cache it before dispatching the print job. However, if the url is pointed through your css and not passed directly into the print job using the `css` property, the lib won't have a way to cache it first, therefore, the print job will get triggered before the style is available locally. We already have another ticket for this, linking it here for reference: #285 . I hope we can find a solution for that.

Closing this ticket since the only active issue is reported in another. If necessary, please create a fiddle or sandbox replicating the issue and reopen this. Thank you guys.
