### ISSUE TITLE
Print Json with custom CSS

### ISSUE THREAD

**Issue by huyngvu** [crabbly/Print.js#369]
I'm using Print Json in my project, and it's working well.
But now I have another request, some fields will be disabled, maybe will show in dark color.

Could I do it, please help me.
Many thanks

**Comment by crabbly** [comment]
Hey @huyngvu, currently, the library doesn't offer a way to create cell identifies when printing a table with the JSON data. The JSON feature was added as a quick way to print JSON, without much customization. Maybe things could change in the future (PRs are welcomed 🥇 ).

One way I would solve this today, is to create my own HTML layout, probably a hidden element (so it doesn't show to the user before printing), and then print this HTML element, instead of the JSON data directly. Printjs supports HTML.

By doing that, we can have full control of the actual layout, hiding or modifying specific data cells or columns depending on the business need.

Hope this helps.

**Comment by huyngvu** [comment]
Thanks Crabbly, I customized your script for my project. Yes may be I will create PR very soon :)
Thanks so much!
