### ISSUE TITLE
console.log(element.nodeType) in dist/print.js

### ISSUE THREAD

**Issue by dm-AS** [crabbly/Print.js#394]
In dist/print.js line 143 is a console.log(element.nodeType) left in the html.js part. 
I can't gulp-uglify it away because of the string.

**Comment by lucas-burdell-karmak** [comment]
Seeing the same problem. The version in NPM does not match what is in GitHub, else we could remove the offending code with a PR...

**Comment by zenghao1203** [comment]
When to update

**Comment by simon-woo** [comment]
the source code not find console.log(element.nodeType), why? want to remove it in product env.

**Comment by amrita-syn** [comment]
Still waiting on this. Its been a while.

**Comment by dolthead** [comment]
@crabbly If I fork master and npm install that, this issue is fixed. When will you publish your latest changes to npmjs to resolve this? Thank you!

**Comment by crabbly** [comment]
Hey guys, sorry for the long delay. I haven't had time to work on the lib in a while. I published a new version this week to npm, v1.1.0 with a couple of fixes, including the removal of this console log. Please run npm update to get it. Let me know if any issues. 
Also, if anybody is interested in helping with the lib maintenance, please send me an email. I would love to prevent the lib from not getting attention for such a long time due to my lack of free time. Thanks again for you help!
