### ISSUE TITLE
Throws an error in FF

### ISSUE THREAD

**Issue by Nicky-DT** [crabbly/Print.js#417]
I'm trying to print a PDF file from a blob, so I have a link which looks like blob:http://some_host/blob_id
It works fine everywhere except FF, where it returns an error "TypeError: win is null".
I've searched for the reasons and found that in FF there are some problems when you try to call window.open(url, '_blank') for downloadable links (https://support.mozilla.org/en-US/questions/1165910). So I think the problem is somewhere here.

**Comment by crabbly** [comment]
Hey @Nicky-DT, thanks for the info. Since printing pdfs is currently not supported in Firefox (https://printjs.crabbly.com/#browsers), the lib will open the file in a new tab. I just tested the examples in the documentation page using the latest version of Firefox and it seems to be working as expected. Please make sure your local blob is formatted properly. I would expect it to open in a new tab.

Also, Mozilla just fixed a very long running bug that prevented us from trying to update the lib to support Firefox. 
https://bugzilla.mozilla.org/show_bug.cgi?id=911444

I hope we can add support for it soon. I will play with it once I have some time. A PR would be greatly welcomed. 

If you are still having issues where the document is not showing in a new tab in Firefox, please reopen this with a fiddle or codepen replicating the issue.

Thank you.
