### ISSUE TITLE
print with empty blank spaces

### ISSUE THREAD

**Issue by RudyHalim** [crabbly/Print.js#419]
Hi, 

I have setup my thermal printer and can print from test page. I have searched about print from web for several days and reached your page. But can only print with empty blank spaces whatever i type.

Here is my code:

> `<script type="text/javascript" src="https://printjs-4de6.kxcdn.com/print.min.js"></script>`
> `<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">`
> 
> `<div id="printable">`
> `	<h1>hello world</h1>`
> `	<h5>boo</h5>`
> `</div>`
> 
> `<button onclick="printJS('printable', 'html')">PRINT</button>`

Can someone please advise me on what did i need to do to fix this?

Many thanks folks!

**Comment by crabbly** [comment]
Hi @RudyHalim, this code should work. Try passing `targetStyles: ['*']`, it may help. Although I wouldn't recommend using this for large HTML print jobs. Also, try playing with `addEventListener()` instead of the `onclick` option. Lastly, if you have any custom CSS, try passing it to the lib using the `style` or `css` properties.
Hope this helps.
