### ISSUE TITLE
Two requests for Image

### ISSUE THREAD

**Issue by kinguru** [crabbly/Print.js#424]
Hi!
PrintJS makes 2 http requests for call:
printJs('http://....myimage.jpg', 'image')

As image is runtime generated on server-side, I getting an overhead CPU. 
Why do printJS need 2 requests for same resource?

Thanks

**Comment by jcnventura** [comment]
The first one is when it adds the image into the DOM, and the second when it adds it to the iframe (or when that iframe is printed).

I think the only way to avoid this is to load into a base64 dataURL and then add that to the DOM.

**Comment by crabbly** [comment]
Hi @jcnventura, this behavior is currently expected. Since the lib leverages the browser cache, this should only be an issue when browsers have their cache turned off.

![print-js-image-load](https://user-images.githubusercontent.com/16927940/92291524-1f683300-eee7-11ea-82cf-3f85d9fb25c8.png)

However, I do agree that it would be better to prevent this. I think the base64 idea with a local blob may work. 

I haven't had much time to maintain the lib in a while, I'll focus on other bugs instead and won't be making this change. I'll close the issue since the behavior is currently expected, but a PR would be awesome! Thank you.
