### ISSUE TITLE
SVG not rendering correctly

### ISSUE THREAD

**Issue by webbexpert** [crabbly/Print.js#428]
Hi! I've got a couple SVGs (mermaid diagrams) based on https://mermaidjs.github.io/#/
These do not appear to print correctly.. If you can point me in the direction where SVG's are rendered/styled perhaps I can setup a PR for correction
Let me know your thoughts! Thanks in advance! 

Example diagram:
::: mermaid
sequenceDiagram
    participant Web Client
    participant Web Server
    participant Azure Container
    Web Client-->>Web Server: Page Request
    Web Server-->>Azure Container: Resource SAS Request 
    Azure Container-->>Web Server: Resource
    Web Server-->>Web Client: Streamed Resource
:::

Rendered output:

![image](https://user-images.githubusercontent.com/6935487/79709702-c3727a00-8277-11ea-8079-f89413c24ddd.png)

**Comment by crabbly** [comment]
Hi @webbexpert, first, sorry for the delay on this. My guess is that the issue was with the svg not being loaded before the print job was dispatched. I would preload them first before calling the lib to dispatch the print job. 

When it comes to printing SVGs, the lib seems to be processing them as expected. Here is a fiddle showing a print result that includes an SVG image:
https://jsfiddle.net/crabbly/eoxo57jo/11/

Hope this help.
