### ISSUE TITLE
Not working with dynamically generated PDF files

### ISSUE THREAD

**Issue by hemantvikram** [crabbly/Print.js#429]
Hi Team,

My client has a requirement to redirect the generated PDF to get printed directly on the printer. The client is only using chrome browser to run the application. The application is a JSP web application running on the Tomcat server version 9.0. 

When I have the button defined along with the PDF file statically in the JSP page, I get the modal dialog and everything is working as expected. But when I set the generated PDF file dynamically, I don't see the modal dialog popping and neither there are errors logged in the Developer console. If I copy and paste the same path of the PDF file in the browser, the browser shows the PDF file. 

Can you please assist how to trace down the issue? Below is the code I use to set the PDF file dynamically. filePath holds the PDF file name and the path formed is also valid.

```
<script type="text/javascript">
var filePath = "<%=filePath%>";
filePath = filePath.split('/').join('\\')
$("#aPDFFile").attr("onclick", printJS('/AD/files/'+filePath));
document.getElementById("aPDFFile").click();
</script>
```

Thanks,
Hemant.

**Comment by crabbly** [comment]
Hi @hemantvikram, this is probably due to the PDF not being completely loaded by the library. My recommendation is to first fetch the PDF contents into a blob, or base64, and only then create the print job with the library. 

When using base6, the library actually creates the blob for you. You can see the code here:
https://github.com/crabbly/Print.js/blob/847687d57f73478d0312d4d5c8d81cac6bbbab6f/src/js/pdf.js#L41

The documentation has an example printing a base64 PDF
https://printjs.crabbly.com/

Hope this helps.
