### ISSUE TITLE
Support paperSize and paperOrientation parameters when printing images

### ISSUE THREAD

**Issue by jcnventura** [crabbly/Print.js#434]
I'd like to be able to provide a paperSize and paperOrientation parameter when printing an image.

The logic here would be that instead of setting 100% width to the image, that print-js would instead calculate the highest width/height that would enable the image to fit within the aspect ratio of the provided  paper size (A4 / letter / etc.) in the given paper orientation ('landscape', 'portrait').

For bonus points, maybe we could also add horizontalAlignment and verticalAlignment properties to specify how to handle the empty space on the page.

There seems to be about 10 page sizes that the library would need to know the aspect ratio.

See https://www.w3.org/TR/css-page-3/#typedef-page-size-page-size for the list of 10 page sizes supported by the CSS Paged Media module.

Depending on browser support, the library could then even provide this CSS on the document being printed:

```
@page {
  size: A4 landscape;
}
```

Note: probably obsoletes issue #421.

**Comment by jcnventura** [comment]
It seems 76% of installed browsers already support that @page specification:

https://caniuse.com/#feat=css-paged-media

**Comment by crabbly** [comment]
Hi @jcnventura, the library already exposes two options to customize the print style. We can use the `style` or `css` properties to pass custom page orientation or any other style.
https://printjs.crabbly.com/#configuration
Adding the orientation option to the API is not a bad idea, but since the lib already has support through CSS, its nice to keep its code base as small as possible. Thank you.
