### ISSUE TITLE
When I print HTML Form doesn't print an image inside my form.

### ISSUE THREAD

**Issue by VWDemon** [crabbly/Print.js#436]
I have a form for print with different data including an image inside as a logo,  when I print my form doesnt print my logo, the rest of document prints great, but my logo gets empty.

![imagen](https://user-images.githubusercontent.com/65246457/81725696-d67a0380-944b-11ea-9335-4ff27d8567c2.png)

I'm using this code:
`	<body onload="printJS('printJS-form', 'html', {
				honorMarginPadding: false
				})">`

**Comment by JandersonConstantino** [comment]
Please, could you create an example in Codepen?

**Comment by crabbly** [comment]
Hi @VWDemon, this may be due to the browser having its cache disabled. The library is currently relying on this for HTML or image printing. It would be nice to prevent this, but unfortunately I'm currently not planning on changing this behavior. O PR would be welcomed. Ref: #424 
If necessary, please reopen this issue with more information. Thank you.
