### ISSUE TITLE
Print multi page Pdf in mobile Safari

### ISSUE THREAD

**Issue by pablopaul** [crabbly/Print.js#44]
In mobile Safari (I am testing on iOS 10.3.1) only the first page of a multi page Pdf gets printed. 

Any idea how to fix this?

**Comment by crabbly** [comment]
Not really. I would have to run a test. Have you tried to print the pdf directly without using the library?

**Comment by pablopaul** [comment]
@crabbly here is the print screen when I directly open http://printjs.crabbly.com/docs/large_printjs.pdf and use native iOS print option - 3 pages:

![image](https://cloud.githubusercontent.com/assets/635526/25393141/fe476544-29da-11e7-939c-80e92b222541.png)

and here of I print the same Pdf via `print.js` - 1 page:

![image](https://cloud.githubusercontent.com/assets/635526/25393168/0d5879f6-29db-11e7-9df9-e52440928561.png)

**Comment by crabbly** [comment]
That's a new one. Somehow Safari mobile is not rendering the pdf properly when loaded with the library. I'll take a look into this.

**Comment by pablopaul** [comment]
I also asked the same question here http://stackoverflow.com/questions/43587792/force-print-dialog-in-mobile-safari-for-multi-page-pdf

**Comment by Sammoewel** [comment]
Ran into exactly the same issue, would be great if someone could find a solution for this one.
I also notice that PDF's (single page and multi-page) are scaled down a bit in size.

And, should it help you finding a solution: The URL of the page I'm currently on is printed at the bottom of the page (not the URL of the PDF I'm printing), along with the page number.

**Comment by crabbly** [comment]
This is still an issue with safari mobile. 
I think we should just identifying the browser as "not supported", and force the pdf to be opened by IOS. 

Thoughts?

**Comment by crabbly** [comment]
Closing this in favor of #33. Keeping all browser compatibility issues under that ticket.

**Comment by AnalyzePlatypus** [comment]
It seems like the iOS Safari print method takes the first page of the PDF, and handles it as if it were an HTML page, with the following behaviors:

* A blank PDF is created, independent of the PDF you're trying to print.
* The first page of the your PDF is added to the blank PDF as an inline image (incl. downsampling)
* Footers containing the page URL and the printing timestamp are added.
* The system PDF is passed to the printer stack.

This appears to be a Safari behavior for web-based printing, so there's nothing this library can do to work around it.

**Comment by tobias77X** [comment]
@crabbly 
I have just encountered this error that you can only print the first page of multi-page PDFs. As you have closed this issue with #33 - should this one be resolved or is iOS Safari just not supported?
I was not sure, therefore I checked the large-pdf-sample on your website, but the same bug here...
Would be great, if you could give me a short hint. Thx!

**Comment by crabbly** [comment]
That's correct. Safari mobile is currently not supported, unfortunately. We should update the browser support table on the documentation page, with mobile browsers.

**Comment by ryanrupp** [comment]
For PDF printing, `window.open(pdfUrl)` + `window.print` seems to work for Safari mobile. It looks like this library uses hidden iframe printing though. For PDF at least there's a check [here](https://github.com/crabbly/Print.js/blob/08d002d43a9c383cc26fedbae3c8a6f597666917/src/js/init.js#L140) for IE where it just does this effectively (but doesn't call `window.print`) - I guess in theory Safari could do this here. Other challenge is it's hard to determine Safari on iPad vs desktop due to "request as desktop" on iPad making it so the user agent just looks like a desktop at that point. Iframe based printing appears to work on Safari desktop just not mobile, so if you need to differentiate the two you would probably have to just cater to the lowest denominator then which is do window.open based printing for Safari regardless of desktop vs mobile.

Also for `window.open` printing the action needs to be inline with a user action I believe to avoid getting a pop-up notification prompt.

Edit - to clarify I actually had to hack this a bit with random timeouts... and the `setInterval` call to try to auto-close the tab afterward is pretty hacky/reliant on Safari specific behavior to ignore  (or not process) the `close` call if the print dialog is open. But, I guess it "sort of" works in Safari mobile. Full code with massive comments around the hacks:

```
const printWindow = window.open(printSrcUrl);
printWindow.onload = () => {
    // Note using a zero delay setTimeout here to workaround issue that even when putting
    // print() inside of onload iOS Safari will prompt that the page hasn't loaded completely before print was called
    printWindow.setTimeout(() => {
        printWindow.focus();
        printWindow.print();

        // Try to automatically close the window after print
        // This is iOS Safari specific behavior we're relying on here. Essentially, there's not a good callback
        // currently to detect that the print dialog closed because
        // 1) "afterprint" event is only supported if the top level page is HTML where as it's PDF likely in this case
        // 2) there doesn't appear to be any other events (like focus) that we could hook into to detect
        // This works in iOS because if you call window.close() while the print dialog is open nothing happens. This isn't
        // true to other browsers though. Because of this though we can just periodically try to close the window until it works.
        printWindow.setInterval(() => printWindow.close(), 300);
    });
};
```
