### ISSUE TITLE
How to load font-face in printjs

### ISSUE THREAD

**Issue by TranManhThang96** [crabbly/Print.js#450]
I loaded the font with print js and it was pending. Is there any way to preload the font before printing ?

**Comment by TranManhThang96** [comment]
![issue](https://user-images.githubusercontent.com/32483289/86229453-edbaaf00-bbb9-11ea-8fa0-853dc3e3f1d3.PNG)

**Comment by crabbly** [comment]
This is probably due to the font-face being imported by your CSS code. The lib won't know that the font dependency is still being loaded inside the iframe, used by the lib to prepare the print job. I'm planning to implement a solution for this, but currently the lib doesn't have support. If this isn't the case, just pass the font-face dependency to the library using the `css` property and that should do the trick.
https://printjs.crabbly.com/#configuration

Please feel free to reopen this issue with more information if necessary. Thank you.
