### ISSUE TITLE
documentTitle option does not work with base64 encoded data

### ISSUE THREAD

**Issue by galzetta** [crabbly/Print.js#451]
Using the `documentTitle` option to set the name of the file does not work when specifying base64 data  on the latest Chrome version (Google Chrome 83.0.4103.116).

```
printJS({
    printable: base64data,
    type: 'pdf',
    base64: true,
    documentTitle: object.name,
});
```

The filename seems to be the name of the url object created by `createObjectURL`. Maybe this is not fixable? Should this issue be opened against the browsers?

**Comment by crabbly** [comment]
When using base64data the library is expecting a pdf document. When printing pdf documents, the browser won't attach the document time, only on html, image or json prints. This is actually a good thing, since it allow us to print exactly the document without any browser enforced header or footer (managed by user browser settings and not our JS lib). Good luck.
