### ISSUE TITLE
Bug when printing from Chrome IOS

### ISSUE THREAD

**Issue by GLuchtenberg** [crabbly/Print.js#472]
First of all, hi everyone, you're doing a great job with this lib and it is really saving my ass :P 

I am facing a really annoying problem when trying to use printJS on iOS chrome, on Safari it works well...
When I try to print a file, the print dialog actually opens with the current page with some CSS bugs, instead of the file I've sent to the `printJS()` function, is there anything that I can do?

If there is something on the lib that I can change, I would be happy to create a PR as well

**Comment by crabbly** [comment]
Hey @GLuchtenberg, I'm glad to hear the lib is helping, big thanks to all these contributors:
https://github.com/crabbly/Print.js/graphs/contributors

About the issue, the current mobile browser support is quite weak. This is due to mobile browsers API not been compatible with some of the lib implementation. We have another long running thread about browser support here #33 .
Eventually we also need to update the documentation to differentiate support between desktop and mobile.

I'll run some tests in IOS Chrome whenever I have a chance and will post an update here. Thank you.

**Comment by crabbly** [comment]
Tested and confirm the issue. Unfortunately, mobile browser support is currently quite weak due to different behavior between mobile and desktop browsers. I'll will close this is favor of #33. I'm keeping that issue open until we cover all mobile browser issues. I hope we can improve this soon. Thank you for reporting this.
