### ISSUE TITLE
print.js ignore background-color and linear-gradient

### ISSUE THREAD

**Issue by MennaRamadan** [crabbly/Print.js#480]
while using printJS I figured out that background-color and linear-gradient ignored 
So can anyone help please
Here is my code snippet here I used html2canvas to take image screenshot then pass it to printJS
`html2canvas(document.body, {` 
        `onrendered: function(canvas)`  
        `{`
           ` var img = canvas.toDataURL(); `  
            `canvas.toBlob(function(blob) {`
               ` printJS({`
                    `printable: img,`
                    `type: 'image',`
                    `honorColor : true,`
                    `scanStyles: false`
                  ` }`
                `});`
            `});`
       ` }`
    });
`

**Comment by crabbly** [comment]
Hey @MennaRamadan, if you use html2canvas to create an image, print that image with printjs, and the print result doesn't include the background color, then the issue is with html2canvas, not printjs. Try to add an id to the html you want to print, and then pass that to print.js dispatching a html print job instead of image. If that doesn't work, please create a fiddle or sandobox displaying the issue and reopen this. Hope this helps.
