### ISSUE TITLE
Chrome extensions breaking Print.js

### ISSUE THREAD

**Issue by andersonbispo** [crabbly/Print.js#486]
Hi there.

I used the Print.js 1.4.0 in a project and it didn't work in 2 of 4 computers that I've tested with Chrome. While debugging, I realized that when I used the private mode, it worked in all computers. Then, assuming it's was because of extensions, I disabled the extensions one by one and I got a different extension breaking the Print.js in each computer.

Do you know why some extensions can affect the Print.js and how can we prevent this?

Congrats for this awesome project.

**Comment by crabbly** [comment]
Hey @andersonbispo, I'm sorry to hear about this. Unfortunately there is no way for us to know without debugging each of these scenarios. Extension by extension. As well what type of print jobs are being affected (pdf, html, json, image). And even if we actually find out exactly where or why the extension is blocking the print job, I'm not sure we could overcome that :(

I'll close this issue since there isn't much we can do right now. Feel free to reopen if you want compile more data and create more discussions around it. 

Thank you for reporting this.
