### ISSUE TITLE
HTML title and url not printed in IE11

### ISSUE THREAD

**Issue by vschimpf** [crabbly/Print.js#488]
When using HTML type on IE11, the documentTitle option is not working, no title is printed. And the url of the page says "about:blank" instead of the url. This can be reproduced in the documentation page https://printjs.crabbly.com/ by clicking the button "Print Form with Header".
I could verify that the browser print (ctrl + P) it works fine, actually prints the page title and the page url on the page, so I think it is an issue on the library.

**Comment by crabbly** [comment]
Looks like IE is ignoring the title added to the iframe used by the library. The browser doesn't provide any other for us to manipulate this data, at least as far as I know. I'll close this issue since there isn't anything we can do with the library itself to add support for this param in IE, unfortunately. Feel free to reopen this issue. Thank you.
