### ISSUE TITLE
background-color is ignored

### ISSUE THREAD

**Issue by LeaGoarant** [crabbly/Print.js#490]
I am trying to use `background-color` in my CSS file using `targetStyles: ['*']` for `html` to call it, but `background-color` is never applied. And when I change it to `color`, it works as intended.

**Comment by crabbly** [comment]
Hi @LeaGoarant, by default most browser's won't print the HTML background color. Try printing this very page and see how the browser ignores the grey background color from Github's top navigation bar. If you go into your browser settings, you should see an option to enable and disable this. Since this is a local user browser preference, we can't control it with Javascript alone.

**Comment by LeaGoarant** [comment]
I had no idea about that ! Just want to add if other people cross this problem, that it can be easily fix by adding `color-adjust:exact;`.

**Comment by crabbly** [comment]
Awesome! I wasn't aware of this. Thanks for sharing, Lea.

For ref.: https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust

**Comment by jekorx** [comment]
I found that ```color-adjust: exact;``` doesn't work in chrome 89, while ```-webkit-print-color-adjust: exact;``` is effective. You can try adding a browser prefix.  
![1](https://user-images.githubusercontent.com/17465469/111098730-0f5c9a80-857f-11eb-98ec-49b24e00f2f1.jpg)
