### ISSUE TITLE
font-size is not needed

### ISSUE THREAD

**Issue by GuoSirius** [crabbly/Print.js#492]
The maxWidth and fontSize styles, set separately for each clone element, have too high a priority, causing the custom print style not to take effect and causing confusion

```javascript
export function collectStyles (element, params) {
  const win = document.defaultView || window

  // String variable to hold styling for each element
  let elementStyle = ''

  // Loop over computed styles
  const styles = win.getComputedStyle(element, '')

  for (let key = 0; key < styles.length; key++) {
    // Check if style should be processed
    if (params.targetStyles.indexOf('*') !== -1 || params.targetStyle.indexOf(styles[key]) !== -1 || targetStylesMatch(params.targetStyles, styles[key])) {
      if (styles.getPropertyValue(styles[key])) elementStyle += styles[key] + ':' + styles.getPropertyValue(styles[key]) + ';'
    }
  }

  // need delete start
  // Print friendly defaults (deprecated)
  // This line of code will cause the custom font style not to take effect
  elementStyle += 'max-width: ' + params.maxWidth + 'px !important; font-size: ' + params.font_size + ' !important;'
  // need delete end

  return elementStyle
}
```

**Comment by GuoSirius** [comment]
Or introduce a configuration item to determine whether the style needs to be spliced

**Comment by crabbly** [comment]
Hi @GuoSirius, thanks for pointing this out. We need to go ahead and remove this option for good. It's already deprecated. This is scheduled to happen in v2. It may take a couple or few months before we release it. In the meantime, I'm not sure how to fix this without breaking the current behavior. Since the logic is applying a default font, removing this would be a breaking change. Adding another prop to the Api wouldn't be a good solution. 

Let me know if you have any other ideas. Otherwise. we will keep pushing to release v2 as soon as possible.

**Comment by crabbly** [comment]
Closing this issue since it's being handled with the v2 release. I hope we can it out soon. Thank you.

**Comment by zhengwhizz** [comment]
where is the v2 ??
