### ISSUE TITLE
some time image load some time not 

### ISSUE THREAD

**Issue by imadarif** [crabbly/Print.js#507]
Images some time show some time not, i have to cache clear then image will start showing. whats the issue ? 

using this plugin version "print-js": "^1.0.54",

**Comment by crabbly** [comment]
Interesting, I haven't seen that before. The lib tries to cache images before dispatching the print job. If the user's browser cache is disabled, that could be an issue, but that doesn't seem to be your case. Another issue could be with images being fetched by JS or CSS instead of directly tagged into HTML img elements. If you could please create a jsfiddle or sandbox replicating this behavior, please reopen this issue so we can debug it together. Thanks.
