### ISSUE TITLE
Empty space on small screens

### ISSUE THREAD

**Issue by OlesyaKlochko** [crabbly/Print.js#509]
Hi @crabbly! I need your help again 🙂  I've faced with the problem, when we print our reports from HTML on the different screens. If its a small screen then we have some empty space on the right. I guess it could be fixed by adding `minWidth` property to the printable element container during cloning process (not to all children like we have it for `maxWidth` property). Or probably you know how to fix this problem in the other way? Many thanks in advance for you help. 🙂 

Bellow you can see screenshot examples:
![image](https://user-images.githubusercontent.com/22976204/98945218-7f381700-24f2-11eb-9677-e5aca4caa169.png)
![image](https://user-images.githubusercontent.com/22976204/98945382-bad2e100-24f2-11eb-9023-625f73c3b7d2.png)

**Comment by crabbly** [comment]
Hi @OlesyaKlochko, sorry for delay. I agree with the print media query approach. This way the layout can still be responsive adapting to different screen sizes, but the print media query will rule how to display that HTML in the print results. 

Also, keep in mind that the lib has a `maxWidth` property with a default value. You may want to manipulate that as well. 
https://github.com/crabbly/Print.js/blob/master/src/js/init.js#L21
Unfortunately this property can't be removed from v1 since it would break the API for users relying on it. It will however be removed in v2. I hope we can release that soon.
