### ISSUE TITLE
Safari / Print More than once 

### ISSUE THREAD

**Issue by theRiley** [crabbly/Print.js#510]
When using Safari, the first time I print everything works fine. If I close the Print Dialog generated by the browser, then try to print again, I get a new dialog from Safari:

`"This webpage is trying to print. Do you want to print this webpage?".`

Sometimes clicking "Print" here will actually work, sometimes it won't.

It looks like the same thing happens when I use Safari for the demo pages at https://printjs.crabbly.com

Any help or ideas on how to remove that behavior? Thanks so much, love this package alot!

**Comment by crabbly** [comment]
Hi @theRiley, I have seen this behavior with Safari. Looks like it will display that on any page that uses javascript to create print jobs. I guess their goal was to protect the user from sites trying to dispatch multiple unwanted jobs, but it's probably creating more issues that anything positive. At least they are not blocking the print job, as long the user confirms the print request. I hope they remove this flag eventually, or possibly create a better algorithm to identify the user click event, since that is what is trigger the print job. In the meantime I can't think of anything we can do with javascript alone, unfortunately. I'll close this issue since this isn't a lib issue. Feel free to reopen if necessary.
