### ISSUE TITLE
The printed font has become the normal font size

### ISSUE THREAD

**Issue by 929496959** [crabbly/Print.js#511]
System:(windows7 ultimate sp1 x64)

browser:(Microsoft Edge 是最新版本。
版本 87.0.664.30 (官方内部版本) beta (64 位))

Print.js version:1.5

html:
```
<form method="post" action="#" onclick="return false;" runat="server" id="printJSform" name="printJSform">
<span class="h3">XXXXXXXXXX</span>
<h3>XXXXXXXXXX</h3>
</from>
```

script:

```
printJS({ printable: "printJSform", type: "html", css: ['../bootstrap/css/bootstrap.min.css?v1'], targetStyles: ["*"] });
```

**Comment by yaodebian** [comment]
I have a problem. In my html page, font-size was set to different sizes and then font-size wasn't changed on the printed preview page. At last, I just used a simple print script to deal with it instead of using this npm package. Have you solved your problem? In addition, could the repository author confirm whether it is a issue that font-size is not changed? Hope the repository author can answer my question, thank you.

**Comment by 929496959** [comment]
> I have a problem. In my html page, font-size was set to different sizes and then font-size wasn't changed on the printed preview page. At last, I just used a simple print script to deal with it instead of using this npm package. Have you solved your problem? In addition, could the repository author confirm whether it is a issue that font-size is not changed? Hope the repository author can answer my question, thank you.

It's not solved. I tried something similar to yours

**Comment by 929496959** [comment]
There is a euphemistic way to achieve the Title Effect, using canvas to draw the title

**Comment by crabbly** [comment]
Hey guys, the library has properties for font family and size, and those properties have default values. They are already deprecated and will be removed in the next version of the library. I hope we can release that soon. In the meantime, please manipulate these values.
https://github.com/crabbly/Print.js/blob/master/src/js/init.js#L46

Also, for better print results, instead of using `targetStyles`, I would recommend using the `style` and `css` properties instead. You can pass your stylesheets into the `css` property, or simple styling with `style`.

To manipulate the print results even more, I recommend also exploring print media queries. This will give you a better control over the print results without affecting your interface layout. Hope this helps. Feel free to reopen this issue if necessary.

**Comment by liamngth** [comment]
@crabbly I am facing an issue when setting font-size. Can you help to check if there is any issue with the code?
I am using vue framework
template: 

`
<template>
  <div id="hidden_template" >
    ....
    <div class="header-t1">This is a header</div>
    .....
  </div>
</template>
`

`methods: {  
    print() {  
      printJS({  
        printable: this.$refs.pdf.$el.id,  
        type: 'html',  
        style: '#hidden_template {display: block!important}',  
        css: 'a css file inserted here',  
        targetStyles: ['*'],  
      });  
    },  
}`  


style.css here:


`
... some css code here
@media print {  
.header-t1 {  
  font-size: 20pt;  
}  
...  
`

in print preview, the font size isn't changed.
