### ISSUE TITLE
printJS is not defined

### ISSUE THREAD

**Issue by Miirwan** [crabbly/Print.js#513]
I just download (print.min.css - print.min.js - v1.5.0) to work with in my project used Thymeleaf , I added script to my  page 
    `<script th:src="@{/static/resources/assets/js/print.min.js}"></script>`
and Style 
    `<link th:href="@{/static/resources/assets/style/print.min.css}">`

here my js code 
```
function generatePDF() {
        printJS({ printable: 'report-to-print', type: 'html' });
}
```
when i try to access into the target page i have this error : Uncaught ReferenceError: printJS is not defined , do I miss something to import ! thnks in advance

**Comment by crabbly** [comment]
Hey @Miirwan, looks like the issue is with your import statement. Just make sure the lib is loaded into your environment before calling the `printJS` function. The current version (v1) is still exposing a global method. Btw, that may change in the future. I would recommend using npm and importing the library that one. Its our best option for JS dependency management. Hope this help.
