### ISSUE TITLE
Image print 3 pages instead of 1

### ISSUE THREAD

**Issue by kinguru** [crabbly/Print.js#515]
I've an image PNG which need to be printed.
printJS('image url here.png', 'image')

In Google Chrome it opens print preview dialog and show me 3 pages - 1st blank, 2nd my image, 3rd blank.
I tried to remove margins/paddings by adding "css" like * { margin:0, padding:0 } it fixed 1st page. Now i have 2 pages. 1st page my image, 2nd page is blank. 

In case i download image directly and print it via same browser (image open with Google Chrome) it display correct print dialog preview with 1 page only and my image in it. Same printer, same paper size, same orientation.

How i could remove 2nd blank page, while printing with printJS() call?
Please help

**Comment by crabbly** [comment]
Hi @kinguru, my guess is that the issue is with the image URL. If you look into the lib documentation page, there are examples printing images, and I was unable to replicate the issue there. If you create a fiddle or codesanbox replicating this, I could def look more into it. Feel free to reopen this issue.

**Comment by chttiu** [comment]
I have encountered it as well, and I resolved it in the following way. 
```
@media print {
       @page { 
            margin: 0;
        }

        body {
            margin: 0;
            padding: 0;
        }
}
```
