### ISSUE TITLE
Safari not printing dynamic text

### ISSUE THREAD

**Issue by Calcul8or** [crabbly/Print.js#523]
I have a form containing numerous fields and three tables that are all dynamically populated, all contained in a div. Printing this div and all of its content in Chrome & Firefox works brilliantly, but in Safari all fields and tables are empty and collapsed.

Any idea what I'm doing wrong?

**Comment by crabbly** [comment]
Hummm I have no idea. It sounds like browser incompatibility with either the app code handling the dynamic data or the library code. If you create a fiddle or codesandbox replicating the issue, I could take a look into it and try to help more. Otherwise is impossible for me to guess where the problem is :(
Closing this for now. Feel free to reopen.
