### ISSUE TITLE
style is not working

### ISSUE THREAD

**Issue by k-kawaa** [crabbly/Print.js#612]
printJS config style is not working.
For example, this link program settings font-color "red" , but it is not working.

https://codesandbox.io/s/printjs-fontsize-forked-g5dtl?file=/src/index.js

**Comment by jq5** [comment]
try this:

body {margin: 0;font-size: 36px;} .card-number {font-size: 52px!important;color: red!important;}",

or 

body {margin:0;font-size:36px;} .card-number {font-size:52px!important;color:red!important;}",

instead of:

body { margin: 0; font-size: 36px; } .card-number { font-size: 52px!important; color: red!important; }",

removing spaces makes it work for me :)

hope this helps,,

J

**Comment by hariacharya80** [comment]
seems fine!

**Comment by k-kawaa** [comment]
Thank you so much!
I apologize for late replay.
